### ISSUE TITLE
cannot find the env-variable HOST in "env" section in github action workflow

### ISSUE THREAD

**Issue by jonadeline** [73h/gae-app-yaml-replace-env-variables#1]
Hi,

Im trying to use this github action but it seems that it's not able to read the env section from the workflow and Im not able to figure out why. All the secrets have been set in my Github repo .

Here is the step in my job using the action. 

```
    steps:
      - uses: actions/checkout@v2
      - uses: 73h/gae-app-yaml-replace-env-variables@v0.1
        env:
          HOST: ${{ secrets.HOST }}
        with:
          app_yaml_path: 'gcp-staging.yaml'
```

My gcp-staging.yaml file :

```
runtime: nodejs16
instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: $SECRET_HOST
```

The error triggered when running the job :

```Traceback (most recent call last):
  File "/app/main.py", line 35, in <module>
    replace_env_variables_in_app_yaml_file()
  File "/app/main.py", line 27, in replace_env_variables_in_app_yaml_file
    raise Exception(f"cannot find the env-variable {key} in \"env\" section in github action workflow")
Exception: cannot find the env-variable HOST in "env" section in github action workflow
```

Is there something wrong in my yaml files ? 
Thanks in advance for your help.

**Comment by 73h** [comment]
Hi,

thanks for the hint. You have named the ENV variable in the gcp-staging.yaml file "$SECRET_HOST". So it was looking for an ENV variable "SECRET_HOST" and did not find it.

Correct is like this.

```
env_variables:
  HOST: $HOST
```

But unfortunately the error message was wrong and confusing, I changed that.

I hope this helps you.

Best regards
